#
# Module manifest for module 'logging'
#
# Generated by: System Administrator
#
# Generated on: 2025-08-02
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSUniversalLogging.psm1'

# Version number of this module.
ModuleVersion = '3.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'a7b8c9d0-e1f2-3456-7890-abcdef123456'

# Author of this module
Author = 'PowerShell Community'

# Company or vendor of this module
CompanyName = 'Open Source'

# Copyright statement for this module
Copyright = '(c) 2025 PowerShell Community. MIT License.'

# Description of the functionality provided by this module
Description = 'A fully generic, reusable, and extensible PowerShell logging module that can be used in ANY PowerShell project. 100% application-agnostic with no hardcoded dependencies. Features automatic line number detection, call stack analysis, wrapper function support, multiple log levels, and configurable paths. Perfect for scripts, modules, automation tools, installers, monitoring solutions, or any PowerShell application. Zero dependencies - works with PowerShell 5.1+.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Initialize-Logging',
    'Write-AppDeploymentLog',
    'Write-EnhancedLog',
    'Handle-Error',
    'Get-ParentScriptName',
    'Get-CallingScriptName',
    'Get-SessionLogDirectory',
    'Get-CSVLogPath',
    'Write-CSVLog',
    'Remove-OldCSVLogs',
    'Get-CurrentUser',
    'Start-UniversalTranscript',
    'Stop-UniversalTranscript',
    'Sync-TranscriptState',
    'Update-TranscriptState',
    'Get-LoggingModuleVersion'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'PSUniversalLogging.psm1',
    'PSUniversalLogging.psd1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Logging', 'Diagnostics', 'Debug', 'LineNumbers', 'CallStack', 'Universal', 'RMM', 'SYSTEM', 'Enterprise', 'Automation')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/aollivierre/PSUniversalLogging/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/aollivierre/PSUniversalLogging'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## Version 3.0.0 - 2025-08-03
### BREAKING CHANGES
- Removed ALL hardcoded paths and application-specific references
- Default base path changed to generic $env:ProgramData\UniversalLogs
- Network logging path must now be explicitly configured via Initialize-Logging

### Added
- NetworkLogPath parameter to Initialize-Logging for optional centralized logging
- Truly universal - no more Win11Scheduler or SCCM server references

### Fixed
- Module is now genuinely application-agnostic as originally intended
- All paths are fully configurable with sensible generic defaults

## Version 2.2.0 - 2025-08-03
### Changed
- Simplified logging levels to short, clear names:
  - Information → INFO
  - Warning → WARNING  
  - Error → ERROR
  - Debug → DEBUG
  - Success → SUCCESS
- All scripts now use consistent uppercase short levels
- Enhanced mapper supports both old and new names for compatibility

## Version 2.1.0 - 2025-08-03
### Added
- Support for 'Success' logging level
- Green color output for success messages in console
- Proper semantic differentiation between Information and Success

### Changed
- Extended ValidateSet to include Success level
- Updated console output switch to handle Success level

## Version 2.0.0 - 2025-08-02
### Fixed
- Line number detection now works correctly with wrapper functions
- Improved call stack navigation logic
- Fixed issues with SYSTEM context execution

### Added
- Comprehensive module documentation
- Module manifest file (.psd1)
- Version tracking

### Changed
- Enhanced call stack analysis algorithm
- Better handling of wrapper functions like Write-DetectionLog

## Version 1.0.0 - 2024-01-01
### Initial Release
- Basic logging functionality
- File and console output
- CSV logging support
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}